# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://paul-yuchao-dong.github.io/hellonbdev/"

git_url = "https://github.com/paul-yuchao-dong/hellonbdev/tree/{branch}/"

def custom_doc_links(name): return None
